web/urls.py
from django.conf.urls import url
from django.contrib import admin
from dw_app.views import index, register_page, general_indicators, products_diff
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^general/$', general_indicators, name='general'),
    url(r'^difference/$', products_diff, name='difference'),
    url(r'^$', index, name='home'),
]

dw_app/forms.py
import re
from .models import User
from django.core.exceptions import ObjectDoesNotExist
from django import forms

class RegistrationForm(forms.Form):
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())
    api_pass = forms.CharField(label='api password')

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

    def clean_email(self):
        email = self.cleaned_data['email']

        try:
            User.objects.get(email=email)
        except ObjectDoesNotExist:
            return email
        raise forms.ValidationError('This email is already in use.')

    def clean_api_pass(self):
        if 'api_pass' in self.cleaned_data:
            api_pass = self.cleaned_data['api_pass']
            if len(api_pass) <= 254:
                return api_pass
            raise forms.ValidationError('API password should be less or equal to 254 characters length')
        raise forms.ValidationError('You should provide your API pass')

class DateRangeForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

    def __init__(self, *args, **kwargs):
        initial_start_date = kwargs.pop('initial_start_date')
        initial_end_date = kwargs.pop('initial_end_date')
        required_val = kwargs.pop('required')

        super(DateRangeForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].initial = initial_start_date
        self.fields['start_date'].required = required_val
        self.fields['end_date'].initial = initial_end_date
        self.fields['end_date'].required = required_val

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<meta content="initial-scale=1, width=device-width" name="viewport"/>

	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static 'jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery.comiseo.daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">

	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="{% static '/js/requester.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/csrf_tokenizer.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{% static '/js/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/jquery.comiseo.daterangepicker.js' %}"></script>


	<title>{% block title %}Django Simple Login{% endblock %}</title>
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Datawiz API demo</a>
        </div>
          <div class="collapse navbar-collapse" id="navbar">
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'general' %}">General</a></li>
                        <li><a href="{% url 'difference' %}">Sales dynamics</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'logout' %}">Log Out</a></li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'register' %}">Register</a></li>
                        <li><a href="{% url 'login' %}">Log In</a></li>
                    </ul>
                {% endif %}
          </div>
      </div>
    </div>


  <hr>
    <hr>
    <hr>
  <main>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
  </main>
  <hr>

</body>
</html>

templates/difference.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="hide">From {{ daterange_form.start_date }} to {{ daterange_form.end_date }}</div>

    <h2>Products sales dynamics information</h2>

    <div class="container">
        <blockquote>
            <p>Chose the date range and wait a wile before data table will appear.</p>
            <p>If you chose big date range - drink a cup of coffee and relax before long waiting.</p>
            <footer>Bender</footer>
        </blockquote>
    </div>


    <div class="alert alert-danger" id="error_msg" style="display: none;">

    </div>

    <script>
        $(function() { $("#dt_range").daterangepicker(
            {
                presetRanges: [
				    {text: 'All available range',
                    dateStart: function() { return moment(document.getElementById('id_start_date').value) },
                    dateEnd: function() { return moment(document.getElementById('id_end_date').value) }
				    }],
                dateFormat: 'dd.mm.yy',
			    altFormat: 'dd.mm.yy',
                change: function(event, data) { diffAJAX() }
            }
        ); });
    </script>

    <input id="dt_range" name="e1">

    <br>
    <br>
    <br>
    <div id="records_block">

    </div>

{% endblock %}

templates/general.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="hide">From {{ daterange_form.start_date }} to {{ daterange_form.end_date }}</div>

    <h2>General salary information</h2>

    <div class="alert alert-danger" id="error_msg" style="display: none;">

    </div>

    <script>
        function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
        }

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    // Only send the token to relative URLs i.e. locally.
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                }
            }
        });

    </script>

    <script>
        $(function() { $("#dt_range").daterangepicker(
            {
                presetRanges: [
				    {text: 'All available range',
                    dateStart: function() { return moment(document.getElementById('id_start_date').value) },
                    dateEnd: function() { return moment(document.getElementById('id_end_date').value) }
				    }],
                dateFormat: 'dd.mm.yy',
			    altFormat: 'dd.mm.yy',
                change: function(event, data) { dateRangeChangeAJAX() }
            }
        ); });
    </script>

    <input id="dt_range" name="e1">

    <br>
    <br>
    <br>
    <div id="records_block">

    </div>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
            You are currently logged in as {{ user.email }}
        {% else %}
            Welcome, guest.
    {% endif %}

    <br>
    <br>

    {% if info %}
        <div class="panel panel-default">
          <div class="panel-heading">Information</div>
        </div>
        <div class="panel panel-primary panel-info">
          <div class="panel-heading">General</div>
          <div class="panel-body">
              <p>Username: {{ info.name }}</p>
              <p>Timezone: UTC {% if info.timezone >= 0 %} + {% else %} - {% endif %} {{ info.timezone }}</p>
              <p>Root category: {{ info.root_category }}</p>
              <p>Observation period: {{ info.date_from|date:"d.m.Y" }} - {{ info.date_to|date:"d.m.Y" }}</p>
          </div>
        </div>

        <div class="panel panel-primary panel-info">
          <div class="panel-heading">Shops</div>
          <div class="panel-body">
                <table class="table" id="white_top">
                <tr>
                    <th>Shop ID</th>
                    <th>Shop name</th>
                </tr>
              {% for shop_id, shop_name in info.shops.items %}
                  <tr>
                    <td>{{ shop_id }}</td>
                      <td>{{ shop_name }}</td>
                  </tr>
              {% endfor %}
                </table>
          </div>
        </div>
    {% else %}
        <img src="{% static '/img/bender.jpg' %}" class="img-rounded" alt="Login to view content"">
    {% endif %}
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% block head %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <form action='.' method='post'>
    {% csrf_token %}
        <fieldset>
            <div class="form-group">
                <input autocomplete="off" autofocus class="form-control" id="id_username" name="username" placeholder="Email" type="email"/>
            </div>
            <div class="form-group">
                <input class="form-control" id="id_password" name="password" placeholder="Password" type="password" value=""/>
            </div>
            <div class="form-group">
                <button class="btn btn-default" type="submit">Log In</button>
                <input type="hidden" name="next" value="{{ next|escape }}" />
            </div>
        </fieldset>
    </form>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}User Registration{% endblock %}
{% block head %}User Registration{% endblock %}

{% block content %}

    <h2>Register</h2>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <form action='.' method='post'>
    {% csrf_token %}
        <fieldset>
            <div class="form-group">
                <input autocomplete="off" autofocus class="form-control" id="id_email" name="email" placeholder="Email" type="email" required />
            </div>
            <div class="form-group">
                <input class="form-control" id="id_password1" name="password1" type="password" placeholder="Password"  value="" required />
            </div>
            <div class="form-group">
                <input class="form-control" id="id_password2" name="password2" type="password" placeholder="Re-enter password"  value="" required />
            </div>
            <div class="form-group">
                <input autocomplete="off" autofocus class="form-control" id="id_api_pass" name="api_pass" placeholder="API password" type="text" required />
            </div>
            <div class="form-group">
                <button class="btn btn-default" type="submit">Register</button>
            </div>
        </fieldset>
    </form>
{% endblock %}